# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4a089556c1f7f038e33b36efe262e2d27acb8806626ea053ac8627cb8d1b94198927dd946840f20a369588900b2306d0389d096344bdbc6c62f001cfcad9c86

test:
  secret_key_base: 6295ea0d949cc513f003fdfa52d45c2310d3cf82de5ae2c841f425656373dd1bc902d7262341e70fc0afebf2803d6ff2a494dbadbf27599e043c4bbb5ac85ce4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
